### ISSUE TITLE
« Hors gel mode »

### ISSUE THREAD

**Issue by hobeur** [Benoit3/Diematic#1]
Bonjours Benoit
Merci pour le partage
Avant de faire le montage je veux être sûr qu’il répond à mon besoin
Je souhaite la passer en mode hors gel si j’oublie après avoir quitté mon domicile 
Et l’allumer 1 jour avant d’arriver
(Le bouton 1 de la commande)
Est ce possible via l’application ?
Je n’ai pas trouvé la réponse dans la documentation.
Merci

**Comment by Benoit3** [comment]
Bonjour,

oui tout à fait, c'est possible : "Temporary anti freezing, is no more available as it was not correctly settable through the Diematic 3 Modbus interface, but permanent antifreezing mode has replaced it"

Le mode antigel permanent fonctionne . A vérifier quand même avec votre chaudière.
Cordialement

**Comment by hobeur** [comment]
Merci beaucoup pour la réponse, super projet
