### ISSUE TITLE
Could you add a picture, or a link to the 2 wire cable and a mini DIN connector with four pins

### ISSUE THREAD

**Issue by hobeur** [Benoit3/Diematic#2]
Hi,

before buying something, i'd like to be sure,
I'm looking to buy the "2 wire cable and a mini DIN connector with four pins"
Could you put a link, a technical description, or a pitcure of what you have ?

Thanks for your help

**Comment by Benoit3** [comment]
You can view technical description here:
https://github.com/Benoit3/Diematic/blob/master/ReadMeImages/ModBusMiniDinConnection.png

As these connectors are small and not easy to sold, I bought an old s VHS cable (like https://fr.rs-online.com/web/p/cordons-din/7424282) and cut it
